<?php

namespace Database\Seeders;

use App\Models\ImportDuty;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ImportDutySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $arrys = [
 
            ["name"=>"AC Compressor \/ Parts","value"=>"27"],
            ["name"=>"Agriculture Equipment","value"=>"10.5"],
            ["name"=>"Air Conditioners","value"=>"27"],
            ["name"=>"Amplifiers","value"=>"0"],
            ["name"=>"Aquarium","value"=>"10.5"],
            ["name"=>"Art, Antiques Collectibles","value"=>"10.5"],
            ["name"=>"Auto and Motorcycle Accessories","value"=>"27.0"],
            ["name"=>"Baby stroller","value"=>"27.0"],
            ["name"=>"Basket Balls","value"=>"10.5"],
            ["name"=>"Bearings","value"=>"27.0"],
            ["name"=>"Beauty Supplies","value"=>"10.5"],
            ["name"=>"Beauty Supplies Hair weaving","value"=>"27.0"],
            ["name"=>"Bed & Mattress","value"=>"27.0"],
            ["name"=>"Bicycle Parts","value"=>"10.50"],
            ["name"=>"Books","value"=>"0"],
            ["name"=>"Books & Magazines","value"=>"0"],
            ["name"=>"Cable","value"=>"10.5"],
            ["name"=>"Cameras","value"=>"0"],
            ["name"=>"Candy","value"=>"0"],
            ["name"=>"Car Alarm","value"=>"27"],
            ["name"=>"Car Care Items","value"=>"10.5"],
            ["name"=>"Car Parts \/ Accessories","value"=>"27"],
            ["name"=>"Cards","value"=>"10.5"],
            ["name"=>"Carpets & Mats & Rugs","value"=>"27"],
            ["name"=>"Cars","value"=>"27"],
            ["name"=>"Casette Tapes","value"=>"0"],
            ["name"=>"Cd Rom","value"=>"0"],
            ["name"=>"Cd Rom Drive","value"=>"0"],
            ["name"=>"Cd's And Dvd's (Empty Disk)","value"=>"0"],
            ["name"=>"Cd's And Dvd's (With Content)","value"=>"10.5"],
            ["name"=>"Christmas Lights","value"=>"27"],
            ["name"=>"Christmas Trees","value"=>"27"],
            ["name"=>"Christmas Trees - Natural","value"=>"17"],
            ["name"=>"Clothes","value"=>"10.5"],
            ["name"=>"Coffee","value"=>"10.5"],
            ["name"=>"Coffe Maker","value"=>"27"],
            ["name"=>"Compressor","value"=>"10.5"],
            ["name"=>"Computer Accessories","value"=>"0"],
            ["name"=>"Computer Fan","value"=>"0"],
            ["name"=>"Computer, Hardware","value"=>"0"],
            ["name"=>"Computer, Monitors","value"=>"0"],
            ["name"=>"Computer, Software","value"=>"0"],
            ["name"=>"Computers","value"=>"0"],
            ["name"=>"Contact Lens","value"=>"0"],
            ["name"=>"Cooking Pan","value"=>"10.5"],
            ["name"=>"Cosmetics","value"=>"10.5"],
            ["name"=>"Cricket Bats","value"=>"10.5"],
            ["name"=>"Cricket Pads \/ Balls","value"=>"10.5"],
            ["name"=>"Cycling Helmet","value"=>"13"],
            ["name"=>"Cycling Pads","value"=>"10.5"],
            ["name"=>"Decoration And Design","value"=>"27"],
            ["name"=>"Dental Drills","value"=>"10.5"],
            ["name"=>"Dental Fillings","value"=>"10.5"],
            ["name"=>"Dental Supplies","value"=>"10.5"],
            ["name"=>"Diskettes","value"=>"0"],
            ["name"=>"Diving Equipment","value"=>"10.5"],
            ["name"=>"Documents","value"=>"0"],
            ["name"=>"Drills","value"=>"10.5"],
            ["name"=>"Dvd Player","value"=>"0"],
            ["name"=>"Electric Circular Saw","value"=>"10.5"],
            ["name"=>"Electronics, Digital Cameras","value"=>"0"],
            ["name"=>"Electronics, Game Console","value"=>"17"],
            ["name"=>"Electronics, Sound System","value"=>"0"],
            ["name"=>"Electronics, Tv","value"=>"0"],
            ["name"=>"Electronics, Video Cameras","value"=>"0"],
            ["name"=>"Electronics,  Nintendo Wii\/PlayStation\/Xbox Video Games","value"=>"17"],
            ["name"=>"Electronics,  Video Games","value"=>"0"],
            ["name"=>"Electronics, Walkman","value"=>"0"],
            ["name"=>"E-Readers","value"=>"0"],
            ["name"=>"Escalator Parts","value"=>"10.5"],
            ["name"=>"Fax Line","value"=>"10.5"],
            ["name"=>"Fax Machines","value"=>"10.5"],
            ["name"=>"Fire Extinguisher","value"=>"10.5"],
            ["name"=>"Fishing Rods","value"=>"10.5"],
            ["name"=>"Food And Beverage","value"=>"10.5"],
            ["name"=>"Food Spices\/Marinades","value"=>"10.5"],
            ["name"=>"Food Supplements","value"=>"10.5"],
            ["name"=>"Football Shoes","value"=>"13"],
            ["name"=>"Footballs","value"=>"10.5"],
            ["name"=>"Games And Hobbies","value"=>"17"],
            ["name"=>"Games \"Board Games\"","value"=>"17"],
            ["name"=>"Games \"Cards\/Uno\/ And More\"","value"=>"17"],
            ["name"=>"Games \"Domino\"","value"=>"17"],
            ["name"=>"Gardening Machine","value"=>"27"],
            ["name"=>"Garden Chairs & Tables","value"=>"27"],
            ["name"=>"Golf Bags","value"=>"13"],
            ["name"=>"Golf Balls","value"=>"10.5"],
            ["name"=>"Guitar & Parts","value"=>"10.5"],
            ["name"=>"Gym Pack","value"=>"10.5"],
            ["name"=>"Hand Tools Eg. Saw","value"=>"10.5"],
            ["name"=>"Hard Drive","value"=>"0"],
            ["name"=>"Hearing Aids","value"=>"0"],
            ["name"=>"Home And Garden Decor","value"=>"27"],
            ["name"=>"Household Items","value"=>"10.5"],
            ["name"=>"Household Items Pillow","value"=>"27"],
            ["name"=>"Household Items Chairs","value"=>"27"],
            ["name"=>"Household Items Dining Set","value"=>"22"],
            ["name"=>"Household Items Dining Set W\/O Table","value"=>"27"],
            ["name"=>"Household Items Dining Set W Table","value"=>"22"],
            ["name"=>"Ink Cartridge","value"=>"10.5"],
            ["name"=>"Ipad","value"=>"0"],
            ["name"=>"Jewelry - Real","value"=>"0"],
            ["name"=>"Jewerly Fancy","value"=>"13"],
            ["name"=>"Keyboards","value"=>"0"],
            ["name"=>"Kindle","value"=>"0"],
            ["name"=>"Kitchen Utensils","value"=>"10.5"],
            ["name"=>"Labels","value"=>"10.5"],
            ["name"=>"Liquid Toner","value"=>"10.5"],
            ["name"=>"Marine Engine Parts","value"=>"10.5"],
            ["name"=>"Medicine And Health Products","value"=>"10.5"],
            ["name"=>"Memory (Camera)","value"=>"0"],
            ["name"=>"Memory (Computer)","value"=>"0"],
            ["name"=>"Modems","value"=>"0"],
            ["name"=>"Monitors","value"=>"0"],
            ["name"=>"Mother Boards","value"=>"0"],
            ["name"=>"Mouse","value"=>"0"],
            ["name"=>"Musical Instruments","value"=>"10.5"],
            ["name"=>"Oil","value"=>"0"],
            ["name"=>"Office Furniture","value"=>"27"],
            ["name"=>"Office Supplies","value"=>"10.5"],
            ["name"=>"Orchids","value"=>"17"],
            ["name"=>"Orchids - Fake","value"=>"27"],
            ["name"=>"Orthopedic Items","value"=>"10.5"],
            ["name"=>"Paint","value"=>"10.5"],
            ["name"=>"Pens","value"=>"10.5"],
            ["name"=>"Phones","value"=>"10.5"],
            ["name"=>"Phone Screens","value"=>"10.5"],
            ["name"=>"Phones Accessories","value"=>"10.5"],
            ["name"=>"Photo Paper","value"=>"10.5"],
            ["name"=>"Plates","value"=>"10.5"],
            ["name"=>"Plumbing Materials","value"=>"10.5"],
            ["name"=>"Point Of Sale Printer","value"=>"10.5"],
            ["name"=>"Power Tools","value"=>"10.5"],
            ["name"=>"Pressure Washer","value"=>"10.5"],
            ["name"=>"Printers","value"=>"10.5"],
            ["name"=>"Ring Light & Stand","value"=>"27"],
            ["name"=>"Scanners","value"=>"10.5"],
            ["name"=>"Seeds","value"=>"10.5"],
            ["name"=>"Sheets Set Only \"Bed\"","value"=>"10.5"],
            ["name"=>"Sheet Set & Comforter \"Bed\"","value"=>"27"],
            ["name"=>"Sheets & Curtains","value"=>"27"],
            ["name"=>"Shoes","value"=>"13"],
            ["name"=>"Shoes With Spikes, Studs Or Duds","value"=>"13"],
            ["name"=>"Specialty Shoes","value"=>"13"],
            ["name"=>"Spectacle Frames","value"=>"10.5"],
            ["name"=>"Sporting Goods","value"=>"10.5"],
            ["name"=>"Squash Rackets","value"=>"10.5"],
            ["name"=>"Stationery","value"=>"10.5"],
            ["name"=>"Sunglasses","value"=>"10.5"],
            ["name"=>"Switch Boxes","value"=>"10.5"],
            ["name"=>"Tennis Racquets","value"=>"10.5"],
            ["name"=>"Tennis Shoes","value"=>"13"],
            ["name"=>"Towels","value"=>"10.5"],
            ["name"=>"Toys","value"=>"10.5"],
            ["name"=>"Toys, Games And Hobbies","value"=>"10.5"],
            ["name"=>"Treadmills","value"=>"10.5"],
            ["name"=>"Tires \/ Rims","value"=>"27"],
            ["name"=>"Usb Flash Drives","value"=>"0"],
            ["name"=>"Veterinary Products","value"=>"10.5"],
            ["name"=>"Video Cards","value"=>"0"],
            ["name"=>"Video Games","value"=>"17"],
            ["name"=>"Vitamins","value"=>"10.5"],
            ["name"=>"Volleyballs","value"=>"10.5"],
            ["name"=>"Watches","value"=>"0"],
            ["name"=>"Water Pumps","value"=>"10.5"],
            ["name"=>"Wireless Routers","value"=>"0"],
            ["name"=>"Gym Equipment (Tax Free)","value"=>"0"],
            ["name"=>"Lights","value"=>"10.5"],
            ["name"=>"Beauty Supplies \"Conditioner\/Shampoo\"","value"=>"10.5"],
            ["name"=>"Baking Good \" Moulds and More\"","value"=>"10.5"],
            ["name"=>"Essential oil","value"=>"10.5"],
            ["name"=>"Brushes","value"=>"10.5"],
            ["name"=>"Dog Leash","value"=>"10.5"],
            ["name"=>"Tv Box","value"=>"10.5"],
            ["name"=>"Sewing machine","value"=>"10.5"],
            ["name"=>"Light Bulb","value"=>"13"],
            ["name"=>"Lamp","value"=>"27"],
            ["name"=>"LED Bulb till 7 Watt","value"=>"0"],
            ["name"=>"LED Bulb greater 7 Watt","value"=>"13"],
            ["name"=>"Cigarette Roller Machine","value"=>"10.5"],
            ["name"=>"Air Filter (Home Machine)","value"=>"10.5"],
            ["name"=>"Battery, Laptop ","value"=>"0"],
            ["name"=>"Battery, Disposable","value"=>"10.5"],
            ["name"=>"Battery, Automotive","value"=>"27"],
            ["name"=>"HINGE","value"=>"10.5"],
            ["name"=>"Candle","value"=>"10.5"],
            ["name"=>"Security Camera","value"=>"0"],
            ["name"=>"Key Chain","value"=>"10.5"],
            ["name"=>"Clothes Hanger","value"=>"10.5"],
            ["name"=>"T-shirt Pers Machine","value"=>"10.5"],
            ["name"=>"Brochures\/Envelops","value"=>"0"],
            ["name"=>"Hoverboard","value"=>"10.5"],
            ["name"=>"Roller Blades","value"=>"10.5"],
            ["name"=>"Cups(Metalic)","value"=>"10.5"],
            ["name"=>"Eyeglasses Frame","value"=>"10.5"],
            ["name"=>"Eye Lashes","value"=>"27"],
            ["name"=>"Furniture","value"=>"27"],
            ["name"=>"Fiber Tester","value"=>"10.5"],
            ["name"=>"Wifi Router","value"=>"10.5"],
            ["name"=>"LUGGAGE","value"=>"13"],
            ["name"=>"Glue","value"=>"10.5"],
            ["name"=>"License Plate Frame ","value"=>"10.5"],
            ["name"=>"Grocery bag","value"=>"10.5"]
             
            
        ];

        $count = ImportDuty::count();
        if($count == 0){
            foreach($arrys as $arr){
                $data = ImportDuty::create($arr);
            }
        }
    }
}
