<?php

namespace Database\Seeders;

use App\Models\PickupStation;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PickupStationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $arrys =[ 
            
["name"=>"DEPT NY","email"=>"","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"FL","address"=>"14 TROY HILLS RD UNIT 7","status"=>"0" ,"branch_id"=>"1"],
// ["name"=>"DEPT NY","email"=>"","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"NY 11413","address"=>"182-30 150 SPRINGFIELD GARDENS NY ","status"=>"0"],
["name"=>"RETURN WAREHOUSE","email"=>"","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"NY 11413","address"=>"14703 182ND ST","status"=>"0","branch_id"=>"1"],
// ["name"=>"AMAZON.COM","email"=>"Info@amazon.com","initial_country"=>"us","country_code"=>"1","phone"=>"2708492500","country_id"=>"1","state"=>"Kentuky","address"=>"1050 S COLUMBIA AVE CAMPBELLSVILLE","status"=>"0"],
// ["name"=>"COZY HAND CRAFTED DECOR","email"=>"","initial_country"=>"","country_code"=>"","phone"=>"","country_id"=>"1","state"=>"OLATHE KS 66062","address"=>"16404 S STAGECOACH ST","status"=>"0"],
// ["name"=>"CONCOURSE TEAM EXPRESS","email"=>"","initial_country"=>"","country_code"=>"","phone"=>"","country_id"=>"1","state"=>"SAN ANTONIO TX 78218 ","address"=>"305 DISTRIBUTION DRIVE","status"=>"0"],
// ["name"=>"YD","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"WHIPPANY NJ 07981 ","address"=>"14 TROY HILLS RD UNIT 7","status"=>"0"],
// ["name"=>"UDF GROUP","email"=>"info@noahimports.com","initial_country"=>"","country_code"=>"","phone"=>"","country_id"=>"1","state"=>"SHENZHEN, GUANGDONG PROV.","address"=>"147-48 182ND ST SPRINGFIELD GARDENS","status"=>"0"],
// ["name"=>"NOT FOR RETURN","email"=>"info@noahimports.com","initial_country"=>"","country_code"=>"","phone"=>"","country_id"=>"1","state"=>"ROWLAND HEIGHTS CA 91748","address"=>"345 baldwin park","status"=>"0"],
// ["name"=>"JENISSE ARELLANO BRACHO","email"=>"info@noahimports.com","initial_country"=>"","country_code"=>"","phone"=>"","country_id"=>"1","state"=>"ORLANDO FL","address"=>"10639 DEMILO PL APT 105","status"=>"0"],
// ["name"=>"JERRY","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"6263464019","country_id"=>"1","state"=>"ONTARIO CA 91761 ","address"=>"1521 e franci st, unit a","status"=>"0"],
// ["name"=>"FULFILLLMENT CENTER","email"=>"info@noahimports.com","initial_country"=>"","country_code"=>"","phone"=>"","country_id"=>"1","state"=>"WOODBURY MN 55125-1944","address"=>"2280 VENTURA DRIVE","status"=>"0"],
// ["name"=>"NORDSTROM RACK","email"=>"","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"SAN BERNARDINO CA 92407","address"=>"17335 GLEN HELEN PARKWAY","status"=>"0"],
// ["name"=>"JOE DOE","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"SPRINGFIELD GARDENS NY 11413","address"=>"230-39 ROCKKAWAY JONES","status"=>"0"],
// ["name"=>"ZAZZLE.COM","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"4089832800","country_id"=>"1","state"=>"NOGALES AZ 85621","address"=>"1615 W CALLE PLATA","status"=>"0"],
// ["name"=>"GAP INC","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"8887473702","country_id"=>"1","state"=>"GROVEPORT OH 43125 USA","address"=>"100 GAP INC DIRECT GATEWAY","status"=>"0"],
// ["name"=>"CAFFEE LADRO","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"SEATTLE WA 98119","address"=>"1220 W NICKERSON ST","status"=>"0"],
// ["name"=>"CHASTITY ROGERS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"MARTINSBURG WV 25405","address"=>"1048 AZTEC DR","status"=>"0"],
// ["name"=>"CHRIS JACKSON","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"LONDON KY 40741-7838","address"=>"271 CEDAR POINT DR","status"=>"0"],
// ["name"=>"MR MEDICAL","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"OPA LOCKA FL 33054","address"=>"14000 NW 37TH AVE","status"=>"0"],
// ["name"=>"INTREPID POWERBOATS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"LARGO FL 33773","address"=>"11700 BELCHER RD S","status"=>"0"],
// ["name"=>"MIKE DAMERCHMAN","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"CALERA AL 35040","address"=>"41 N INDUSTRIAL PKWY","status"=>"0"],
// ["name"=>"PARTS N GO","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"LOS ANGELES CA 90040","address"=>"6423 E WASHINGTON BLVD","status"=>"0"],
// ["name"=>"USPS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"MIAMI FL 33166","address"=>"5600 NW 72 AVE.","status"=>"0"],
// ["name"=>"ALAMO APPARELS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"ALLEN TX 75002","address"=>"1600 COVENTRY CT","status"=>"0"],
// ["name"=>"CHINA POST","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"HONG KONG","address"=>"7640 NW 63rd StWU BIEN JINGZHOU DISTRICT","status"=>"0"],
// ["name"=>"MATTHEW LOLYA","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"PALM BAY FL 32907","address"=>"1728 DELWARE ST NW","status"=>"0"],
// ["name"=>"HOU WENZHENG","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"HEBRON KY 41048","address"=>"1200 WORLDWIDE BLVD","status"=>"0"],
// ["name"=>"NORDSTROM RACK","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"SAN BERNARDINO CA 92407","address"=>"17335 GLEN HELEN PARKWAY","status"=>"0"],
// ["name"=>"WESTWOOD RESEARCH","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"MILLSTONE TOWNSHIP NJ 08510","address"=>"9 CHERYL LN","status"=>"0"],
// ["name"=>"AMC","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"EDISON NJ 08820","address"=>"10 PROGESS ST","status"=>"0"],
// ["name"=>"K2 SALES","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"IDAHO FALLS ID 83401","address"=>"2856 N HOLMES AVENUE","status"=>"0"],
// ["name"=>"NUTRAMEDIX LLC","email"=>"steve@nutramedix.com","initial_country"=>"us","country_code"=>"1","phone"=>"5617452917","country_id"=>"1","state"=>"JUPITER FL 33458","address"=>"2885 JUPITER PARK DRIVE Ste 1600","status"=>"0"],
// ["name"=>"AGDAS AZ0300","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"HAYDAR ALIYEV 5 AGDAS AZ 0300 ","address"=>"PO BOX 170643","status"=>"0"],
// ["name"=>"DEPT ATL","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"FRANKLIN PARK IL 60131","address"=>"1055 SESAME STREET","status"=>"0"],
// ["name"=>"STACY&#39;S QUICK STOP AND THRIFT","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"NEW ALBANY MS 38652","address"=>"2011 APPLE TREE LN","status"=>"0"],
// ["name"=>"THE WILLIAM CARTER COMPANY","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"BRASELTON GA 30517","address"=>"625 BBRASELTON PARKWAY","status"=>"0"],
// ["name"=>"COMPLETE PRESS SOLUTIONS HECTOR TORRES","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"4084379410","country_id"=>"1","state"=>"SAN JOSE CA 95131","address"=>"754 CHARCOT AVE","status"=>"0"],
// ["name"=>"IMMUNOTEC INC","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"DALLAS TX 75212","address"=>"3609 PIPESTONE ROAD","status"=>"0"],
// ["name"=>"NIKE","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"8008066453","country_id"=>"1","state"=>"LEBANON IN 46052","address"=>"145 S MOUNT ZION RD","status"=>"0"],
// ["name"=>"MIKE OZKAN","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"FAIRFIELD NJ 07004","address"=>"23 DANIEL RD","status"=>"0"],
// ["name"=>"SHEIN DISTRIBUTION CORPORATION","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"LA PUENTE CA 91744","address"=>"347 S STIMSON AVE","status"=>"0"],
// ["name"=>"Dell","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"6144914603","country_id"=>"1","state"=>"LOCKBOURNE OH 43137","address"=>"4555 CREEKSIDE PKWY","status"=>"0"],
// ["name"=>"ADIDAS DTC","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"WILKES BARRE PA 18705","address"=>"550 NEW COMMERCE BLVD","status"=>"0"],
// ["name"=>"SHAWN ZHANG","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"NEWARK DE 19702","address"=>"622 JACOBSEN CIR","status"=>"0"],
// ["name"=>"FEDEX","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"KNOXVILLE TN 37932","address"=>"10601 MURDOCK DRIVE","status"=>"0"],
// ["name"=>"JFK","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"SPRINGFIELD GARDENS NY 11413","address"=>"14709 182ND ST","status"=>"0"],
// ["name"=>"ECMS EXPRESS INC","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"CITY OF INDUSTRY CA 91748","address"=>"17651 RAILROAD STREET","status"=>"0"],
// ["name"=>"HUAN YU TIAN TAI","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"LEXINGTON KY","address"=>"172 TRADE ST","status"=>"0"],
// ["name"=>"TROY MOONEY","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"MIDLOTHIAN TX 76065","address"=>"6030 CASTLE WAY","status"=>"0"],
// ["name"=>"ANDREW MOLLOY","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"LANCASTER PA 17601","address"=>"1530 MANHEIM PIKE","status"=>"0"],
// ["name"=>"BOXYCHARM","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"KENNESAW GA 30144 ","address"=>"1925 SHILOH ROAD BUILDING 1","status"=>"0"],
// ["name"=>"GRC","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"COPPELL TX 75019","address"=>"840 W SANDY LAKE ROAD","status"=>"0"],
// ["name"=>"ALMA SPAGNOLA","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"MEMPHIS TN 38108","address"=>"1403 STACEY ST","status"=>"0"],
// ["name"=>"JAMES HANDLON","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"NORTH BEACH MD 20714","address"=>"9348 SEA OAT CT","status"=>"0"],
// ["name"=>"POONAM MAHTANI","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"HOLLYWOOD FL 33027","address"=>"1069 SW 147 AVE","status"=>"0"],
// ["name"=>"USED AUTO PARTS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3056884118","country_id"=>"1","state"=>"FL 33054","address"=>"12710 CAIRO LANE OPA-LOCKA ","status"=>"0"],
// ["name"=>"USPS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"MIAMI FL 33166 USA","address"=>"5600 NW 72 AVE.","status"=>"0"],
// ["name"=>"STEFAN VLASKI","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"FRANKLIN WI 53132 USA","address"=>"2987 W DREXEL AVE UNIT 317","status"=>"0"],
// ["name"=>"EXPRESS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"7184542809","country_id"=>"1","state"=>"NJ 08861","address"=>"1000 high st PERTH AMBOY","status"=>"0"],
// ["name"=>"PRO DISTRIBUTING","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"SUN VALLEY CA 91352","address"=>"7668 SAN FERNANDO RD","status"=>"0"],
// ["name"=>"BEAUTY BRANDS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"LENEXA KS 66219","address"=>"15507 W 99TH ST","status"=>"0"],
// ["name"=>"OUTSVILLE","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"KNOXVILLE TN 37922","address"=>"1404 NORTHSHIRE","status"=>"0"],
// ["name"=>"LI CHAU INDUSTRIAL CO, LTD","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"DALIN RD TAYA","address"=>"NO 10, LANE 211","status"=>"0"],
// ["name"=>"ACUITY PAPERS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"CRAWFORDSVILLE IN 47933","address"=>"278 N 400 W","status"=>"0"],
// ["name"=>"SHIPPING DEPT","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"BROOKLYN NY 11220","address"=>"726 64TH ST","status"=>"0"],
// ["name"=>"POORIAM MAHANAH","email"=>"murrybrooks@outlook.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"HOLLYWOOD FL 33027","address"=>"1069 SW 147 AVE","status"=>"0"],
// ["name"=>"HYSAN LLC","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"NEWARK NJ 07112 ","address"=>"370 ELIZABETH AVENUE","status"=>"0"],
// ["name"=>"USFA","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"DAYTON NJ 08810 ","address"=>"200 DOCKS CORNER RD SUITE 221","status"=>"0"],
// ["name"=>"USPS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"WALNUT CA 91789","address"=>"381 S BREA CANYON ROAD","status"=>"0"],
// ["name"=>"C T","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"SAN MARINO CA 91108","address"=>"2275 HUNTINGTON DR #110","status"=>"0"],
// ["name"=>"KEVIN ASCHILIMAN","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"COLUMBUS OH 43220","address"=>"4181 WADDINGTON RD","status"=>"0"],
// ["name"=>"WILLIAM WRIGHT","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"GRAY KY 40734","address"=>"345 HIGGIND RD","status"=>"0"],
// ["name"=>"WALMART.COM","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"SPARTANBURG SC 29303","address"=>"5795 N BLACKSTOCK RD","status"=>"0"],
// ["name"=>"DC MANAGER","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"UNION CITY GA 30349","address"=>"4505 DERRICK INDUSTRIAL PARKWAY","status"=>"0"],
// ["name"=>"Noah Imports Drop Off","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"FL","address"=>"7640 NW 63rd St","status"=>"0"],
// ["name"=>"THE RHINESTONE WORLD","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"BRADENTON FL 34211 ","address"=>"503 LENA RD","status"=>"0"],
// ["name"=>"DEPARTURE OUTDOORS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"WILSONVILLE OR 97070 ","address"=>"25977 SW CANYON CREEK RD SUITE G","status"=>"0"],
// ["name"=>"ANNA SHEN","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"BUFORD GA 30518","address"=>"1700 broadmoor blvd ne suit c","status"=>"0"],
// ["name"=>"ESOTERIC SHOP","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"LAKE DALLAS TX 75065","address"=>"PO BOX 1117","status"=>"0"],
// ["name"=>"CS ORANGECONNEX.COM","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"FRANKLIN PARK IL 60131","address"=>"3701 CENTRELLA STREET","status"=>"0"],
// ["name"=>"JENSEN","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"V5ZV5Z Canada","address"=>"101-1869 SPYGLASS PLACE","status"=>"0"],
// ["name"=>"USKY3 WAREHOUSE","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"HEBRON KY 41048","address"=>"2125 GATEWAY BLVD","status"=>"0"],
// ["name"=>"AUTOSHACK.COM","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"STITTSVILLE ON K2S1E7","address"=>"201 IBER ROAD","status"=>"0"],
// ["name"=>"performance part","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"HEBRON KY","address"=>"2125 GATEWAY BLVD","status"=>"0"],
// ["name"=>"AM AUTO PARTS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"6173149610","country_id"=>"1","state"=>"OLATHE KS 66061 ","address"=>"15250 S GREEN RD DOOR 100","status"=>"0"],
// ["name"=>"JIANG YUANFEI","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"LA PUENTE CA 91744","address"=>"347 S STIMSON AVE B DOOR 17","status"=>"0"],
// ["name"=>"CALI BOYS DEAL","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"MONTCLAIR CA 91763","address"=>"4751 E STATE ST","status"=>"0"],
// ["name"=>"VITALINA","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"ORLANDO FL 32877","address"=>"PO BOX 772319","status"=>"0"],
// ["name"=>"USTX WAREHOUSE","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"HOUSTON TX 77090","address"=>"300 AIRTEX BLVD STE 200","status"=>"0"],
// ["name"=>"PARTS GEEK","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"OLATHE KS 66061","address"=>"15250 GREEN RD","status"=>"0"],
// ["name"=>"PARTS AUTHORITY","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"NEW HYDE PARK NY 11042","address"=>"3 DAKOTA DR SUITE 110","status"=>"0"],
// ["name"=>"BILLY BONS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"STATEN ISLAND NY 10306","address"=>"62 FARRELL CT","status"=>"0"],
// ["name"=>"DHL","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"HOUSTON TX 77060","address"=>"16416 NORTHCHASE DR","status"=>"0"],
// ["name"=>"SOFIO LIQUIDATION","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"FORT LAUDERDALE FL 33330","address"=>"5261 SW 121 ST TER","status"=>"0"],
// ["name"=>"Premier Batteries","email"=>"robert@premierbatteries.com","initial_country"=>"us","country_code"=>"1","phone"=>"3056298666","country_id"=>"1","state"=>"FL","address"=>"1452 NW 82nd Ave","status"=>"0"],
// ["name"=>"ONLINE SELLER","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"COMPTON CA 90220","address"=>"1621 TOWNE CENTER DR","status"=>"0"],
// ["name"=>"ZEELOOL","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"PLANO TX 75074","address"=>"6901 K AVE SUITE 103","status"=>"0"],
// ["name"=>"DEFROST USA","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"MIAMI FL 33178","address"=>"6000 NW 97 AVE UNIT 11","status"=>"0"],
// ["name"=>"MAZDA-PARTS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3109748177","country_id"=>"1","state"=>"TORRANCE CA 90503","address"=>"20626 HAWTHORNE BLVD","status"=>"0"],
// ["name"=>"KUTBI KIROM 1 CENTER","email"=>"info@noahimports.com","initial_country"=>"cw","country_code"=>"599","phone"=>"96665752","country_id"=>"1","state"=>"","address"=>"DUSHANBE. STREET PO BOX 20123 DUSHANBE","status"=>"0"],
// ["name"=>"ROADGET BUSINESS PTE LTD","email"=>"info@noahimports.com","initial_country"=>"cw","country_code"=>"599","phone"=>"96665752","country_id"=>"1","state"=>"","address"=>"DATANG TOWN SANSHUI INDUSTRIAL PARK FOSHAN, PEOP;ES REPUBLIC 528143","status"=>"0"],
// ["name"=>"COUNSELMAN AUTOMOTIVE RECYCLING, LLC","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"2513302700","country_id"=>"1","state"=>"AL","address"=>"3019 ST STEPHENS RD MOBILE AL 36612","status"=>"0"],
// ["name"=>"ONLINE BEAUTY SUPPLY","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"NJ","address"=>"28 IRIS CIRCLE MANALAPAN NJ 07726 USA","status"=>"0"],
// ["name"=>"BADDIEE APPAREL","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"FL","address"=>"PO BOX 983 SHALIMAR FL 32579 USA","status"=>"0"],
// ["name"=>"PITNEY BOWES","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"IN","address"=>"5490 INDUSTRIAL COURT WHITESTOWN IN 46075 USA","status"=>"0"],
// ["name"=>"PC.LIU PANASIAHEIRLOOM","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"IL","address"=>"31444 S KAVANAUGH RD WILMINGTON IL 60481 USA","status"=>"0"],
// ["name"=>"JOE BADER","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"NJ","address"=>"7017 RIDGE AVE","status"=>"0"],
// ["name"=>"WDNJ5","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"NJ","address"=>"1120 ROUTE 22 EAST BRIDGEWATER NJ 08807 USA","status"=>"0"],
// ["name"=>"RETURN SHIPMENTS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"NY","address"=>"84 GRANITE AVE STATEN ISLAND NY 10303 USA","status"=>"0"],
// ["name"=>"THEBLINGBABYSHOP","email"=>"support@theblingbabyy.com","initial_country"=>"us","country_code"=>"1","phone"=>"(305)7176200","country_id"=>"1","state"=>"WA","address"=>"4001 S PINE ST UNIT 111165 TACOMA WA 98411 USA","status"=>"0"],
// ["name"=>"VOOGUEME","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"TX","address"=>"6901 K AVE SUITE 103 PLANO TX 75074 USA","status"=>"0"],
// ["name"=>"SEARS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3054603400","country_id"=>"1","state"=>"MIAMI FL 33145-3014","address"=>"3655 SW 22ND ST","status"=>"0"],
// ["name"=>"THE UPS STORE 4263","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"FL","address"=>"800 OCALA RD TALLAHASSEE FL 32304","status"=>"0"],
// ["name"=>"SCHEELS ALL SPORTS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"NE","address"=>"3030 PINE LAKE ROAD LINCOLN NE 68516 ","status"=>"0"],
// ["name"=>"OUTFITTERS LLC","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"7323289165","country_id"=>"1","state"=>"NJ","address"=>"100 NORTHFIELD AVE EDISON NJ 08837","status"=>"0"],
// ["name"=>"ANNIE TRAN","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"WEST COVINA CA 91790-4420","address"=>"1770 STONOPAH AVE","status"=>"0"],
// ["name"=>"B&H PHOTO VIDEO","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"2124446600","country_id"=>"1","state"=>"08518","address"=>"400 CEDER LN BAY 78","status"=>"0"],
// ["name"=>"BACKYARD CITRUS TREES","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"FL 33859 USA","address"=>"16110 US HIGHWAY 27 LAKE WALES ","status"=>"0"],
// ["name"=>"DEPT CA","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"ONTARIO CA 91761 USA","address"=>"1375 E LOCUST STREET","status"=>"0"],
// ["name"=>"DEPT NJ","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3055933500","country_id"=>"1","state"=>"WHIPPANY NJ 07981 USA","address"=>"14 TROY HILLS RD UNIT 7","status"=>"0"],
// ["name"=>"STEPHANIE JOHNSON","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"HOPEWELL VA 23860 USA","address"=>"304 S 17TH AVE","status"=>"0"],
// ["name"=>"ONLINE SELLER","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"LOS ANGELES CA 90022 USA","address"=>"5620 GRACE PL","status"=>"0"],
// ["name"=>"ELEVATE FULFILLMENT","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"RIVERSIDE CA 92518 USA","address"=>"22340 VAN BUREN BLVD","status"=>"0"],
// ["name"=>"XKH GROUP INC","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"6267747007","country_id"=>"1","state"=>"91761","address"=>" 2220 E. SPRUCE ST ONTARIO ","status"=>"0"],
// ["name"=>"SHIPBOB INC","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"ATLANTA GA 30344-5754","address"=>"3201 CENTRE PKWY STE 500","status"=>"0"],
// ["name"=>"MICRO PLATERS SALES","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3055983300","country_id"=>"1","state"=>"HIGHLAND PARK MI 48203 USA","address"=>"221 VICTOR","status"=>"0"],
// ["name"=>"KNOX AUTO PARTS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"8656904223","country_id"=>"1","state"=>"KNOXVILLE TN 37931 USA","address"=>"8721 OAK RIDGE HWY","status"=>"0"],
// ["name"=>"TNG WORLD WIDE","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3055953300","country_id"=>"1","state"=>"NEW HUDSON MI 48165","address"=>"29683 WILLIAM K SMITH","status"=>"0"],
// ["name"=>"ROADGET BUSINESS PTE LTD JIANG YUANFEI PROLOGIS LOGISTICS CENTER","email"=>"info@noahimports.com","initial_country"=>"","country_code"=>"","phone"=>"","country_id"=>"1","state"=>"FO SHAN 528100","address"=>"DATANG TOWN SANSHUI INDUSTRIAL PARK","status"=>"0"],
// ["name"=>"GUESS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"5029951000","country_id"=>"1","state"=>"40258 USA ","address"=>"10610 FREEPORT DRIVE LOUISVILLE KY ","status"=>"0"],
// ["name"=>"SAVAGE","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057103500","country_id"=>"1","state"=>"PERRIS CA 92571 USA","address"=>"290 E MARKHAM STREET","status"=>"0"],
// ["name"=>"DR. MARTENS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057103500","country_id"=>"1","state"=>"REDLANDS CA 92374 ","address"=>"1651 CALIFORNIA ST","status"=>"0"],
// ["name"=>"DSV SOLUTIONS LLC","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057100500","country_id"=>"1","state"=>"PORT READING NJ 07064","address"=>"1005 Middlesex Ave","status"=>"0"],
// ["name"=>"QING DAO AIMEIER EYELASH CO., LTY","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"HAO","address"=>"ROOM1709 JINGKOULU106 HAO","status"=>"0"],
// ["name"=>"CARNIVAL CAPSULE LLC","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"7868533101","country_id"=>"1","state"=>"BROOKLYN NY 11205 USA","address"=>"141 FLUSHING AVE BUILDING 3 ","status"=>"0"],
// ["name"=>"GYMSHARK","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"30557000000","country_id"=>"1","state"=>"ALLENTOWN PA 18104 USA","address"=>"5185 CRACKERSPORT RD","status"=>"0"],
// ["name"=>"MR WANG","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3055923500","country_id"=>"1","state"=>"China","address"=>"No 9 OPTICS VALLEY","status"=>"0"],
// ["name"=>"MYPROTEIN.COM","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057103500","country_id"=>"1","state"=>"CA 91761","address"=>" 2220 E. SPRUCE ST ONTARIO ","status"=>"0"],
// ["name"=>"PLAZA ARTIST MATERIALS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"NASHVILLE TN 37203 USA","address"=>"633 middleton st633 middleton st","status"=>"0"],
// ["name"=>"JERRY&#39;S ARTARAMA","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"9198786782","country_id"=>"1","state"=>"HENDERSON NC 27526 USA","address"=>"101 PETER GILL RD","status"=>"0"],
// ["name"=>"FINEARTSTORE.COM","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"ROCHESTER NY 14614","address"=>"150 WEST MAIN ST","status"=>"0"],
// ["name"=>"OTCRX4U","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"NORTH BERGEN NJ 07047 USA","address"=>"4201 TONNELLE AVE","status"=>"0"],
// ["name"=>"GRATEFULENTERPRISES","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"BALL GROUND GA 30107 USA","address"=>"8830 WATERSIDE DR","status"=>"0"],
// ["name"=>"NATALIA MCCAUSLAND","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"RANDOLPH NJ 07869 USA","address"=>"GALAXY GLOBAL LOGISTICS 1578 SUSSEX TPKE","status"=>"0"],
// ["name"=>"JOE DOE","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"SPRINGFIELD GARDENS NY 11413 USA","address"=>"17920 149TH AVE","status"=>"0"],
// ["name"=>"QUIET 3PF","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"30571006200","country_id"=>"1","state"=>"DALLAS TX 75220","address"=>"10750 DENTON DR","status"=>"0"],
// ["name"=>"SHIPPING DEPARMENT","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"UPLAND CA 91784","address"=>"1452 ELMHURST WAY","status"=>"0"],
// ["name"=>"QUINDAO DOORES IMPORT & EXPORT CO","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"China","address"=>"ROOM 705 ZHONGHAIGUOJI","status"=>"0"],
// ["name"=>"QUEENBERRY INC","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"SAN JOSE CA 95132","address"=>"1460 SHAFFER DR","status"=>"0"],
// ["name"=>"DC MANAGER","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"UNION CITY GA 30349","address"=>"4505 DERRICK INDUSTRIAL PARKWAY","status"=>"0"],
// ["name"=>"ASOS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"UNION CITY GA 30349","address"=>"4505 DERRICK INDUSTRIAL PARKWAY","status"=>"0"],
// ["name"=>"QINGDAO LADY STYLE COSMETICS CO., LTD","email"=>"info@noahimports.com","initial_country"=>"cn","country_code"=>"86","phone"=>"15615885820","country_id"=>"1","state"=>"SHIBEI CN 266042","address"=>"BUILDING4CENTURY CENTER OF ZHUOYUE","status"=>"0"],
// ["name"=>"HYDROJUG INC","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"OGDEN UT 84404","address"=>"1017 W 600 N SET 1","status"=>"0"],
// ["name"=>"JOE DOE","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"SPRINGFIELD GARDENS NY 11413","address"=>"17920 149TH AVE","status"=>"0"],
// ["name"=>"SHIPPING DEPARMENT","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"UPLAND CA 91784","address"=>"1452 ELMHURST WAY","status"=>"0"],
// ["name"=>"HUBEI SUCESS GLOBAL TRADING","email"=>"info@noahimports.com","initial_country"=>"cn","country_code"=>"86","phone"=>"13123455678","country_id"=>"1","state"=>"WUHAN","address"=>"NO 9 OPTICS VALLEYCHUANYE STREET","status"=>"0"],
// ["name"=>"QUINGDAO TOP STAR EYELASH","email"=>"info@noahimports.com","initial_country"=>"cn","country_code"=>"86","phone"=>"13123456789","country_id"=>"1","state"=>"HUAFU ZAOYUAN","address"=>"1-2-2101 YINZUO HUAFU ZAOYUAN","status"=>"0"],
// ["name"=>"HYPNOTIC","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"LAS VEGAS NV 89109 USA","address"=>"2760 SOUTH HIGHLAND DRIVE","status"=>"0"],
// ["name"=>"SAVAGE","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"LOUISVILLE KY 40214 USA","address"=>"8161 NATIONAL TPKE","status"=>"0"],
// ["name"=>"USA WAREHOUSE 2","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"CHINO CA 91708 ","address"=>"8746 FOUNDERS GROVE ST","status"=>"0"],
// ["name"=>"SAMPURAKA","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"WEST JORDAN UT 84088","address"=>"8152 S WELBY PARK DR","status"=>"0"],
// ["name"=>"GLOBAL PARTS DISTRIBUTOR","email"=>"info@noahimports.com","initial_country"=>"","country_code"=>"","phone"=>"","country_id"=>"1","state"=>"MACON GA 31216","address"=>"3279 AVONDALE AVE","status"=>"0"],
// ["name"=>"FASHION NOVA","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"8008660286","country_id"=>"1","state"=>"SANTA FE SPRINGS CA 90670","address"=>"12588 FLORENCE AVE","status"=>"0"],
// ["name"=>"NEW & USED PARTS FOR LESS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"6196616881","country_id"=>"1","state"=>"SAN DIEGO CA 92154","address"=>"8701 SIEMPRE VIVA RD","status"=>"0"],
// ["name"=>"BEAUTYRENEW","email"=>"","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"POMPANO BEACH FL 33069","address"=>"3456 NW 27TH AVE","status"=>"0"],
// ["name"=>"TAMER ELECTRONICS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"BELLFLOWER CA 90706","address"=>"17021 RIPON AVE","status"=>"0"],
// ["name"=>"BFA","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"HARRISBURG NC 28075 ","address"=>"6420 SADDLE CREEK CT","status"=>"0"],
// ["name"=>"KEREZ SHOP","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"BELLFLOWER CA 90706 USA","address"=>"9535 FLOWER","status"=>"0"],
// ["name"=>"K & K SHOPPING","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"INDIAN TRAIL NC 28079 USA","address"=>"6103 LIGHTED WAY LN","status"=>"0"],
// ["name"=>"RBIHA ABID","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"BROOKLYN NY 11229 USA","address"=>"1829 E 14TH ST","status"=>"0"],
// ["name"=>"ENGRIY STORE","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"CARLISLE PA 17015","address"=>"675 allen rd","status"=>"0"],
// ["name"=>"RIVERO PARTS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"MIAMI FL 33178","address"=>"11800 NW 100TH RD STE 5","status"=>"0"],
// ["name"=>"ABC DEPOT LOGISTICS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"LA PUENTE CA 91746 ","address"=>"13936 VALLEY BLVD BLDG A","status"=>"0"],
// ["name"=>"UNKNOWN SHIPPER","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"UNKNOWN","address"=>"UNKNOWN","status"=>"0"],
// ["name"=>"OE REPLACEMENT","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"MANSFIELD TX 76063","address"=>"1401 HERITAGE PKWY","status"=>"0"],
// ["name"=>"NO ENDORSEMENT","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"DORAL FL 33126","address"=>"1624 NW 82 AVE","status"=>"0"],
// ["name"=>"CROSMAN CORPORATION","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"BLOOMFIELD NY 14469","address"=>"7629 ROUTES 5 & 20","status"=>"0"],
// ["name"=>"BEN CLARK","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"MORRISVILLE NC 27560","address"=>"PO BOX 1402","status"=>"0"],
// ["name"=>"SHIPPING","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"M3J2J5","address"=>"800 FLINT RD","status"=>"0"],
// ["name"=>"RINGKE STORE","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"CARROLLTON TX 75006 ","address"=>"3310 KELLER SPRINGS RD","status"=>"0"],
// ["name"=>"PARTSHAWK","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"WINDSOR LOCKS CT 06096","address"=>"110 OLD COUNTY CIRCLE","status"=>"0"],
// ["name"=>"SLM FULFILLMENT","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"HOUSTON TX 77029","address"=>"3347 rauch st","status"=>"0"],
// ["name"=>"SHIPPER","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"ELYRIA OH 44035 USA","address"=>"580 TERNES AVE","status"=>"0"],
// ["name"=>"JUST MENS SHOES","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"BOCA RATON FL 33431","address"=>"604 BANYAN TRL","status"=>"0"],
// ["name"=>"EXPRESS","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"7184542809","country_id"=>"1","state"=>"PERTH AMBOY NJ 08861 USA","address"=>"1000 high st","status"=>"0"],
// ["name"=>"KUEHNE + NAGEL","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"4043663667","country_id"=>"1","state"=>"FOREST PARK GA 30297","address"=>"2160 anvil block rd.","status"=>"0"],
// ["name"=>"EWELL ELECTRONIC COMMERCE CO LTD","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"WASHINGTON DC 202150","address"=>"NO 419 HESHAN RD HIGH TECH","status"=>"0"],
// ["name"=>"DEPT NJ T2251","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"ELK GROVE VILLAGE IL 60007","address"=>"901 CHASE AVE UNIT A","status"=>"0"],
// ["name"=>"FANATICS INTERNATIONAL","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"BUFFALO NY 14227 ","address"=>"105 FRENCH ROAD","status"=>"0"],
// ["name"=>"WEIFANG KATULA TRADE CO","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"China","address"=>"RM3051 KEJXUEYUAN WENTIPEIX","status"=>"0"],
// ["name"=>"BRENT CELESTINE ENTERPRISE","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"WILLINGBORO NJ 08046","address"=>"19 MANDOLIN LANE","status"=>"0"],
// ["name"=>"UPC BRANDS LLC","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"MIAMI FL 33172","address"=>"2600 NW 112TH AVE","status"=>"0"],
// ["name"=>"JMS TOOL SUPPLY","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"ELKHART IN 46514","address"=>"1428 E BRISTOL STREET","status"=>"0"],
// ["name"=>"UPC BRANDS LLC","email"=>"info@noahimports.com","initial_country"=>"us","country_code"=>"1","phone"=>"3057176200","country_id"=>"1","state"=>"MIAMI FL 33172 ","address"=>"2600 NW 112TH AVE","status"=>"0"]
 
];
        $count = PickupStation::count();
        if($count == 0){
            foreach($arrys as $arr){
                $data = PickupStation::create($arr);
            }
        }
    }
}
