<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\TimeZone;

class TimezoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $timezonesArr = array(
            ['name' => 'Pacific/Midway', 'timezone' => "(GMT-11:00) Midway Island"],
            ['name' => 'US/Samoa'           ,  'timezone' => "(GMT-11:00) Samoa"],
            ['name' => 'US/Hawaii'          ,  'timezone' => "(GMT-10:00) Hawaii"],
            ['name' => 'US/Alaska'          ,  'timezone' => "(GMT-09:00) Alaska"],
            ['name' => 'US/Pacific'         ,  'timezone' => "(GMT-08:00) Pacific Time (US &amp; Canada)"],
            ['name' => 'America/Tijuana'    ,  'timezone' => "(GMT-08:00) Tijuana"],
            ['name' => 'US/Arizona'         ,  'timezone' => "(GMT-07:00) Arizona"],
            ['name' => 'US/Mountain'        ,  'timezone' => "(GMT-07:00) Mountain Time (US &amp; Canada)"],
            ['name' => 'America/Chihuahua'  ,  'timezone' => "(GMT-07:00) Chihuahua"],
            ['name' => 'America/Mazatlan'   ,  'timezone' => "(GMT-07:00) Mazatlan"],
            ['name' => 'America/Mexico_City',  'timezone' => "(GMT-06:00) Mexico City"],
            ['name' => 'America/Monterrey'  ,  'timezone' => "(GMT-06:00) Monterrey"],
            ['name' => 'Canada/Saskatchewan',  'timezone' => "(GMT-06:00) Saskatchewan"],
            ['name' => 'US/Central'         ,  'timezone' => "(GMT-06:00) Central Time (US &amp; Canada)"],
            ['name' => 'US/Eastern'         ,  'timezone' => "(GMT-05:00) Eastern Time (US &amp; Canada)"],
            ['name' => 'US/East-Indiana'    ,  'timezone' => "(GMT-05:00) Indiana (East)"],
            ['name' => 'America/Bogota'     ,  'timezone' => "(GMT-05:00) Bogota"],
            ['name' => 'America/Lima'       ,  'timezone' => "(GMT-05:00) Lima"],
            ['name' => 'America/Caracas'    ,  'timezone' => "(GMT-04:30) Caracas"],
            ['name' => 'Canada/Atlantic'    ,  'timezone' => "(GMT-04:00) Atlantic Time (Canada)"],
            ['name' => 'America/La_Paz'     ,  'timezone' => "(GMT-04:00) La Paz"],
            ['name' => 'America/Santiago'   ,  'timezone' => "(GMT-04:00) Santiago"],
            ['name' => 'Canada/Newfoundland',  'timezone' => "(GMT-03:30) Newfoundland"],
            ['name' => 'America/Buenos_Aires',  'timezone'=> "(GMT-03:00) Buenos Aires"],
            ['name' => 'Greenland'          ,  'timezone' => "(GMT-03:00) Greenland"],
            ['name' => 'Atlantic/Stanley'   ,  'timezone' => "(GMT-02:00) Stanley"],
            ['name' => 'Atlantic/Azores'    ,  'timezone' => "(GMT-01:00) Azores"],
            ['name' => 'Atlantic/Cape_Verde',  'timezone' => "(GMT-01:00) Cape Verde Is."],
            ['name' => 'Africa/Casablanca'  ,  'timezone' => "(GMT) Casablanca"],
            ['name' => 'Europe/Dublin'      ,  'timezone' => "(GMT) Dublin"],
            ['name' => 'Europe/Lisbon'      ,  'timezone' => "(GMT) Lisbon"],
            ['name' => 'Europe/London'      ,  'timezone' => "(GMT) London"],
            ['name' => 'Africa/Monrovia'    ,  'timezone' => "(GMT) Monrovia"],
            ['name' => 'Europe/Amsterdam'   ,  'timezone' => "(GMT+01:00) Amsterdam"],
            ['name' => 'Europe/Belgrade'    ,  'timezone' => "(GMT+01:00) Belgrade"],
            ['name' => 'Europe/Berlin'      ,  'timezone' => "(GMT+01:00) Berlin"],
            ['name' => 'Europe/Bratislava'  ,  'timezone' => "(GMT+01:00) Bratislava"],
            ['name' => 'Europe/Brussels'    ,  'timezone' => "(GMT+01:00) Brussels"],
            ['name' => 'Europe/Budapest'    ,  'timezone' => "(GMT+01:00) Budapest"],
            ['name' => 'Europe/Copenhagen'  ,  'timezone' => "(GMT+01:00) Copenhagen"],
            ['name' => 'Europe/Ljubljana'   ,  'timezone' => "(GMT+01:00) Ljubljana"],
            ['name' => 'Europe/Madrid'      ,  'timezone' => "(GMT+01:00) Madrid"],
            ['name' => 'Europe/Paris'       ,  'timezone' => "(GMT+01:00) Paris"],
            ['name' => 'Europe/Prague'      ,  'timezone' => "(GMT+01:00) Prague"],
            ['name' => 'Europe/Rome'        ,  'timezone' => "(GMT+01:00) Rome"],
            ['name' => 'Europe/Sarajevo'    ,  'timezone' => "(GMT+01:00) Sarajevo"],
            ['name' => 'Europe/Skopje'      ,  'timezone' => "(GMT+01:00) Skopje"],
            ['name' => 'Europe/Stockholm'   ,  'timezone' => "(GMT+01:00) Stockholm"],
            ['name' => 'Europe/Vienna'      ,  'timezone' => "(GMT+01:00) Vienna"],
            ['name' => 'Europe/Warsaw'      ,  'timezone' => "(GMT+01:00) Warsaw"],
            ['name' => 'Europe/Zagreb'      ,  'timezone' => "(GMT+01:00) Zagreb"],
            ['name' => 'Europe/Athens'      ,  'timezone' => "(GMT+02:00) Athens"],
            ['name' => 'Europe/Bucharest'   ,  'timezone' => "(GMT+02:00) Bucharest"],
            ['name' => 'Africa/Cairo'       ,  'timezone' => "(GMT+02:00) Cairo"],
            ['name' => 'Africa/Harare'      ,  'timezone' => "(GMT+02:00) Harare"],
            ['name' => 'Europe/Helsinki'    ,  'timezone' => "(GMT+02:00) Helsinki"],
            ['name' => 'Europe/Istanbul'    ,  'timezone' => "(GMT+02:00) Istanbul"],
            ['name' => 'Asia/Jerusalem'     ,  'timezone' => "(GMT+02:00) Jerusalem"],
            ['name' => 'Europe/Kiev'        ,  'timezone' => "(GMT+02:00) Kyiv"],
            ['name' => 'Europe/Minsk'       ,  'timezone' => "(GMT+02:00) Minsk"],
            ['name' => 'Europe/Riga'        ,  'timezone' => "(GMT+02:00) Riga"],
            ['name' => 'Europe/Sofia'       ,  'timezone' => "(GMT+02:00) Sofia"],
            ['name' => 'Europe/Tallinn'     ,  'timezone' => "(GMT+02:00) Tallinn"],
            ['name' => 'Europe/Vilnius'     ,  'timezone' => "(GMT+02:00) Vilnius"],
            ['name' => 'Asia/Baghdad'       ,  'timezone' => "(GMT+03:00) Baghdad"],
            ['name' => 'Asia/Kuwait'        ,  'timezone' => "(GMT+03:00) Kuwait"],
            ['name' => 'Africa/Nairobi'     ,  'timezone' => "(GMT+03:00) Nairobi"],
            ['name' => 'Asia/Riyadh'        ,  'timezone' => "(GMT+03:00) Riyadh"],
            ['name' => 'Europe/Moscow'      ,  'timezone' => "(GMT+03:00) Moscow"],
            ['name' => 'Asia/Tehran'        ,  'timezone' => "(GMT+03:30) Tehran"],
            ['name' => 'Asia/Baku'          ,  'timezone' => "(GMT+04:00) Baku"],
            ['name' => 'Europe/Volgograd'   ,  'timezone' => "(GMT+04:00) Volgograd"],
            ['name' => 'Asia/Muscat'        ,  'timezone' => "(GMT+04:00) Muscat"],
            ['name' => 'Asia/Tbilisi'       ,  'timezone' => "(GMT+04:00) Tbilisi"],
            ['name' => 'Asia/Yerevan'       ,  'timezone' => "(GMT+04:00) Yerevan"],
            ['name' => 'Asia/Kabul'         ,  'timezone' => "(GMT+04:30) Kabul"],
            ['name' => 'Asia/Karachi'       ,  'timezone' => "(GMT+05:00) Karachi"],
            ['name' => 'Asia/Tashkent'      ,  'timezone' => "(GMT+05:00) Tashkent"],
            ['name' => 'Asia/Kolkata'       ,  'timezone' => "(GMT+05:30) Kolkata"],
            ['name' => 'Asia/Kathmandu'     ,  'timezone' => "(GMT+05:45) Kathmandu"],
            ['name' => 'Asia/Yekaterinburg' ,  'timezone' => "(GMT+06:00) Ekaterinburg"],
            ['name' => 'Asia/Almaty'        ,  'timezone' => "(GMT+06:00) Almaty"],
            ['name' => 'Asia/Dhaka'         ,  'timezone' => "(GMT+06:00) Dhaka"],
            ['name' => 'Asia/Novosibirsk'   ,  'timezone' => "(GMT+07:00) Novosibirsk"],
            ['name' => 'Asia/Bangkok'       ,  'timezone' => "(GMT+07:00) Bangkok"],
            ['name' => 'Asia/Jakarta'       ,  'timezone' => "(GMT+07:00) Jakarta"],
            ['name' => 'Asia/Krasnoyarsk'   ,  'timezone' => "(GMT+08:00) Krasnoyarsk"],
            ['name' => 'Asia/Chongqing'     ,  'timezone' => "(GMT+08:00) Chongqing"],
            ['name' => 'Asia/Hong_Kong'     ,  'timezone' => "(GMT+08:00) Hong Kong"],
            ['name' => 'Asia/Kuala_Lumpur'  ,  'timezone' => "(GMT+08:00) Kuala Lumpur"],
            ['name' => 'Australia/Perth'    ,  'timezone' => "(GMT+08:00) Perth"],
            ['name' => 'Asia/Singapore'     ,  'timezone' => "(GMT+08:00) Singapore"],
            ['name' => 'Asia/Taipei'        ,  'timezone' => "(GMT+08:00) Taipei"],
            ['name' => 'Asia/Ulaanbaatar'   ,  'timezone' => "(GMT+08:00) Ulaan Bataar"],
            ['name' => 'Asia/Urumqi'        ,  'timezone' => "(GMT+08:00) Urumqi"],
            ['name' => 'Asia/Irkutsk'       ,  'timezone' => "(GMT+09:00) Irkutsk"],
            ['name' => 'Asia/Seoul'         ,  'timezone' => "(GMT+09:00) Seoul"],
            ['name' => 'Asia/Tokyo'         ,  'timezone' => "(GMT+09:00) Tokyo"],
            ['name' => 'Australia/Adelaide' ,  'timezone' => "(GMT+09:30) Adelaide"],
            ['name' => 'Australia/Darwin'   ,  'timezone' => "(GMT+09:30) Darwin"],
            ['name' => 'Asia/Yakutsk'       ,  'timezone' => "(GMT+10:00) Yakutsk"],
            ['name' => 'Australia/Brisbane' ,  'timezone' => "(GMT+10:00) Brisbane"],
            ['name' => 'Australia/Canberra' ,  'timezone' => "(GMT+10:00) Canberra"],
            ['name' => 'Pacific/Guam'       ,  'timezone' => "(GMT+10:00) Guam"],
            ['name' => 'Australia/Hobart'   ,  'timezone' => "(GMT+10:00) Hobart"],
            ['name' => 'Australia/Melbourne',  'timezone' => "(GMT+10:00) Melbourne"],
            ['name' => 'Pacific/Port_Moresby',  'timezone'=> "(GMT+10:00) Port Moresby"],
            ['name' => 'Australia/Sydney'   ,  'timezone' => "(GMT+10:00) Sydney"],
            ['name' => 'Asia/Vladivostok'   ,  'timezone' => "(GMT+11:00) Vladivostok"],
            ['name' => 'Asia/Magadan'       ,  'timezone' => "(GMT+12:00) Magadan"],
            ['name' => 'Pacific/Auckland'   ,  'timezone' => "(GMT+12:00) Auckland"],
            ['name' => 'Pacific/Fiji'       ,  'timezone' => "(GMT+12:00) Fiji"]
        );

        foreach($timezonesArr as $arr){
            TimeZone::create($arr);
        }
    }
}
